apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "poeditor-proxy.fullname" . }}
  labels:
    {{- include "poeditor-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "poeditor-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "poeditor-proxy.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            allowPrivilegeEscalation: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          {{- if .Values.image.digest }}
          image: {{ print .Values.image.registry "/" .Values.image.repository "@" .Values.image.digest | quote }}
          {{- else }}
          image: {{ print .Values.image.registry "/" .Values.image.repository ":" (.Values.image.tag | default .Chart.AppVersion) | quote }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.service.port | quote }}
            - name: CONFIG_FILE
              value: /config/config.yml
            {{- with .Values.rootPath }}
            - name: ROOT_PATH
              value: {{ . | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: {{ print .Values.rootPath "/liveness" | quote }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ print .Values.rootPath "/readiness" | quote }}
              port: http
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: {{ .Values.configuration.existingSecret | default (include "poeditor-proxy.fullname" .) }}
            defaultMode: 0444
            optional: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
