{{- if not .Values.configuration.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "poeditor-proxy.fullname" . }}
  labels:
    {{- include "poeditor-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  config.yml: {{ .Values.configuration.inline | toYaml | b64enc }}
{{- end }}
